import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Contact List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <html lang="en">
       <body>
         <nav>
           <ul>
             <a href="/contacts">Home</a>
             <br/>
             <Link href="/add_form">Add Contact</Link>
             <br/>
             <Link href="/contacts/contactId">Contact Info</Link>
             <br/>
           </ul>
         </nav>
         {children}
       </body>
     </html>
   )
 }
 
